### ISSUE TITLE
Had multiple script errors during the build.

### ISSUE THREAD

**Issue by someoneAnyone** [dirkfabisch/Dxtr#11]
Hi! really dig the fact that you're working on this! I've been prototyping UI for a native iOS Nightscout client for a while now working with the REST APIs, but just recently built a xDrip (like last night) and wanted to integrated it into the project after seeing this I might not have to. I built your project last night in the simulator but ran into some problems below are some of what I encountered. I've love to help out if you are interested.

The [README.md](https://github.com/dirkfabisch/Dxtr/blob/master/README.md) mentions some outside dependancies not covered by cocoa pods but doesn't list any specific ways of remedying them.
1. Object Model Generator
   - Problem: Even with [mogenerator](http://rentzsch.github.io/mogenerator/) installed via Brew.sh I still had issues with this script. 
   - Workaround: I removed it (the build step) in my local playpen to get it the app to build.
2. Insert Sketch Ressources
   - Problem: You need to have Sketch installed for this script to work and the app to build.
   - Workaround:
     - a) Improve script to fail gracefully or
     - b) purchase Sketch at $99 app in the [App Store](http://bohemiancoding.com/sketch/store).
     - c) download trial of Sketch at [bohemiancoding](http://bohemiancoding.com/sketch/)

**Comment by dirkfabisch** [comment]
Regarding the mogenerator: I have to remove the build step as well, because their is currently no support for Swift 1.2.

You can insert the sketch ressources with the free [sketchtool](http://bohemiancoding.com/sketch/tool/) from bohemain coding.

**Comment by someoneAnyone** [comment]
@dirkfabisch , Thanks for the sketchtool link completely overlooked that.

**Comment by someoneAnyone** [comment]
Also found that there is a cask available for sketch-tool
brew cask install sketch-tool
