### ISSUE TITLE
mogenerator install instructions.

### ISSUE THREAD

**Issue by ps2** [dirkfabisch/Dxtr#13]
The readme links to the mogenerator site, which installs a binary to /usr/bin/mogenerator.  The build script depends on mogenerator being in /usr/local/bin.  It'd probably help new users to either recommend they brew install mogenerator (which installs to /usr/local/bin), or make the build script use either.

**Comment by henrikcode** [comment]
Thank you ps2. It is very difficult to get this working. hopefully I am one step closer with brew mogenerator. I really could need step-by-step instructions.
Steps:

1.) Open terminal (in Finder, press <cmd>+<shift>+<A>, and then open terminal)
2.) Go to http://brew.sh
3.) Copy statement found in Install Homebrew section into terminal and press <enter>
4.) follow the instructions (press <enter>
5.) In terminal write:  brew install mogenerator
6.) mogenerator is now installed in the right place

**Comment by ps2** [comment]
I got past a few more issues (by removing references to XCGLogger and SwiftOverlays), but now it seems the mogenerator is generating code that doesn't compile on swift 1.2... I'm out of time to experiment with it today.  Maybe later this week. Good luck.

**Comment by ps2** [comment]
Seems like swift 1.2 has thrown a huge wrench into iOS dev, and you can't use swift 1.1 on Xcode 6.3 afaik!

**Comment by dirkfabisch** [comment]
Unfortunately it seams that the development of mogenerator has stopped. As long as I did not plan to adjust the db  model I removed the generation step from the build system and fixed the errors as a result of the Swift 1.2 update.
