### ISSUE TITLE
mogenerator script

### ISSUE THREAD

**Issue by ps2** [dirkfabisch/Dxtr#14]
I'm getting:
`templateDescNamed:@"machine.swift.motemplate": file not found`

I see that the build script is:

```
source ~/.bash_profile
cd "$PROJECT_DIR/Dxtr" && /usr/local/bin/mogenerator --swift -m dxtrDBModel.xcdatamodeld/dxtrDBModel.xcdatamodel  --output-dir ./ModelObjects --template-path ~/.querykit-mogenerator-template
```

What needs to be in .bash_profile, and how do we get ~/.querykit-mogenerator-template?  I'm wondering if having those missing is causing the error I see.

**Comment by ps2** [comment]
Found these instructions in the QueryKit/mogenerator-template project

``` bash
$ brew install --HEAD mogenerator
$ git clone https://github.com/QueryKit/mogenerator-template ~/.querykit-mogenerator-template
```

Now onto the next error:

```
<unknown>:0: error: no such file or directory: '/Users/pete/dev/Dxtr/SwiftOverlays/SwiftOverlays/SwiftOverlays.swift'
Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc failed with exit code 1
```

**Comment by henrikcode** [comment]
Thank you ps2. Now we are on the same level...
Perhaps stupid question, but would it be possible to publish a ready-to-use app?

**Comment by henrikcode** [comment]
I also got this error: 

<unknown>:0: error: no such file or directory: '/Users/pete/dev/Dxtr/SwiftOverlays/SwiftOverlays/SwiftOverlays.swift'
Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc failed with exit code 1

I found that my folders: 
- B68FloatingLabelTextField 
- SwiftOverlays
- XCGLogger
  ...are empty. From GitHub I found the missing files and added them into the empty folders. But the build still fail.

Time to sleep...

**Comment by dirkfabisch** [comment]
Please check the swift 1.2 branch. I cleaned up a lot in this branch.

**Comment by henrikcode** [comment]
downloaded the swift 1.2 branch
pod install
open Dxtr.xcworkspace   in xCode

Get these errors
.../Dxtr-swift_12/Pods/QueryKit/QueryKit/QuerySet.swift:45:34: Cannot assign to 'sortDescriptors' in 'self'
....../Dxtr-swift_12/Pods/QueryKit/QueryKit/QuerySet.swift:118:42: 'AnyObject?' is not convertible to 'T?'; did you mean to use 'as!' to force downcast?
.../Dxtr-swift_12/Pods/QueryKit/QueryKit/Attribute.swift:92:62: '[T]' does not have a member named '_asCocoaArray'
.../Dxtr-swift_12/Pods/QueryKit/QueryKit/Attribute.swift:96:93: Cannot invoke '_asCocoaArray' with no arguments

**Comment by dirkfabisch** [comment]
pull the latest commit from github. that should fix the build errors.

**Comment by henrikcode** [comment]
Thank you! Now I only need to become an apple developer to get the app into the iPhone.
